# SPDX-License-Identifier: Apache-2.0
name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `mise run build --bsp x86_64`
        2. Wait for build to complete
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: dropdown
    id: bsp
    attributes:
      label: BSP / Target Hardware
      description: Which BSP or target hardware is affected?
      options:
        - x86_64
        - orin-nx
        - rk1
        - soquartz
        - All / Not applicable
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your host environment.
      placeholder: |
        - Host OS: Ubuntu 22.04
        - mise version: x.x.x
        - podman/Docker version: x.x.x
        - RAM: 16 GB
        - Disk: SSD, 200 GB free
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Add any relevant log output or screenshots.
      placeholder: Paste log output or attach screenshots...
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information...
    validations:
      required: false
